server:
  port: 7001
spring:
  application:
    name: mti-kafka-stream
  profiles:
    active: dev # 连接环境选择，dev对应application-dev.yml文件；uat对应application-uat.yml文件；prd对应application-prd.yml文件
  cloud:
    consul:
      enabled: true
      host: ${consul.host}     # 配置服务注册中心consul的地址
      port: ${consul.port}     # 配置服务注册中心consul的端口
      discovery:
        enabled: true
        health-check-path: /actuator/health  # 检查通过的路径，注需要consul可以访问
      auth:
        enabled: true
    swagger:
      enabled: true
      basePackage: ltd.fdsa                # swager需要扫描api接口的包名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver # com.mysql.jdbc.Driver
    url: ${database.master.url}
    username: ${database.master.username}
    password: ${database.master.password}
    filters: stat
    filter:
      slf4j:
        enabled: true
        statement-create-after-log-enabled: false
        statement-log-enabled: false
        statement-executable-sql-log-enable: true
        statement-log-error-enabled: true
        result-set-log-enabled: false
    maxActive: 20
    maxWait: 10000
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  logging:
  level:
    ROOT: INFO                              #可以增加不同日志记录的级别
    ltd.fdsa: INFO
#  logstash:
#    destination: ${logstash.destination}    #ELK采集日志地址（logstash)，留空不启用
#    duration: 30
mybatis:
  mapperLocations: classpath:mybatisMappers/**/*.xml
  config-location: classpath:mybatis-config.xml
