server:
  port: 8080
spring:
  application:
    name: demo
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${database.master.driver}
    url: ${database.master.url}
    username: ${database.master.username}
    password: ${database.master.password}
    maxActive: 20
    maxWait: 10000
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    slaves:
      - type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: ${database.master.driver}
        url: ${database.slave_1.url}
        username: ${database.slave_1.username}
        password: ${database.slave_1.password}
      - type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: ${database.master.driver}
        url: ${database.slave2.url}
        username: ${database.slave2.username}
        password: ${database.slave2.password}


  jpa:
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus,druid"
  endpoint:
    health:
      show-details: always
project:
  swagger:
    enabled: true
    basePackages:
      - ltd.fdsa
    api-info:
      title: swagger api
      description: 优雅的restful风格
      terms-of-service-url: http://fdsa.ltd
      version: 1.0
      contact:
        name: zhumingwu
        url: http://fdsa.ltd
        email: zhumingwu@fdsa.ltd
  consul:
    enabled: true
    minutes: 1
    host: 10.168.4.14
    port: 8500
    health:
      enabled: true
  tables:
    enabled: true
    prefix-matches:
      - s*_
      - t*_
      - us*_
    changes:
      append:
        - t_: { prefix: 'test_', suffix: '_result' } #以t_开头的表，前增test_，后增_result
        - s_: { suffix: '_test' } #以s开头的表，后增_test
        - us_: { prefix: 'user_' } #以us_开头的表，前增user_
    remove:
      - _ #移除 _
    replace: { land: 'plan', jiefang: 'liberate' }

logging:
  path: /var/log/${spring.application.name}-${server.port}
  level:
    web: INFO
  pattern:
    console: '[%highlight(%-4level)] %msg%n'
